import re

# ✅ Remove all non-alphabetic characters from string (re.sub())


trigger_words= ['Ableism','Abortion',
'Abusive relationship',
'Abuse',
'Acephobia',
'Ageism',
'Alcohol',
'Alcoholism',
'Amputation',
'Animal abuse',
'Animal death',
'Antisemitism',
'Anxiety',
'Assault',
'Attempted murder',
'Attempted rape',
'Bestiality',
'Blood',
'Bones',
'Branding',
'Bullying',
'Cancer',
'Cannibalism',
'Car accident',
'Cheating',
'Child abuse',
'Child death',
'Childbirth',
'Conversion therapy',
'Cults',
'Death',
'Decapitation',
'Demons',
'Depression',
'Divorce',
'Drugs',
'Eating disorder',
'Emesis',
'Emotional abuse',
'Eugenics',
'Famine',
'Fatphobia',
'Fire',
'Genocide',
'Gore',
'Grief',
'Gun violence',
'Hallucinations',
'Homomisia',
'Homophobia',
'Hospitalisation',
'Hostages',
'Harry Potter References',
'Incest',
'Infertility',
'Kidnapping',
'Lesbiphobia',
'Miscarriage',
'Misgendering',
'Micro-Aggressions',
'Misogyny',
'Murder',
'Needles',
'Occult',
'Pedophilia',
'Physical abuse',
'Plague',
'Poisoning',
'Police brutality',
'Pregnancy',
'Profanity',
'Prostitution',
'PTSD',
'Queerphobia',
'Racism',
'Rape',
'Religion',
'Satan/The Devil',
'School shooting',
'Self-harm',
'Sexism',
'Sexual abuse',
'Sexual assault',
'Sexual harassment',
'Sexually explicit scenes',
'Skeletons',
'Slavery',
'Slut shaming',
'Snakes',
'Spiders',
'Stalking',
'Starvation',
'Suicide',
'Terminal illness',
'Terrorism',
'Torture',
'Transmisia',
'Trauma',
'Transphobia',
'Violence',
'War']

example="This took me approximately a million years to listen to the audiobook, but that's not the book's fault that's just me being not lazy.Despite taking me a long time to read, I think that the pacing did seem consistent as there was pretty much constant action, even in moments of inaction.It dealt with grief and trauma very well, in a way I'd never seen before.The start of a super cool series I think!"
new_str = re.sub(r'[^a-zA-Z]', ' ', example)
review_str=[]
new_str=new_str.split()

re_low=[x.lower() for x in new_str]
trigger_low=[x.lower() for x in trigger_words]

print(list(set(re_low).intersection(trigger_low)))