awk -F ',[[:blank:]]+' '{gsub("Hardback", "Hardcover"); 
gsub("Pasta Dura", "Hardcover"); 
gsub("Capa Dura", "Hardcover");
gsub("Capa dura", "Hardcover");
gsub("Relié", "Hardcover");
gsub("Hardcover In Dust Jacket", "Hardcover");
gsub("Hardcover in dust jacket", "Hardcover");
gsub("Cloth Hardcover", "Hardcover");
gsub("Cloth", "Hardcover");
gsub("cloth", "Hardcover");
gsub("Hardcover, Slipcased", "Hardcover");
gsub("Over-Sized 12"W X 16"H Hardcover", "Hardcover");
gsub("Gebunden", "Hardcover");
gsub("Hardcover ", "Hardcover");
gsub("Gebundene Ausgabe", "Hardcover");
gsub("単行本", "Hardcover");
gsub("Inbunden", "Hardcover");
gsub("Casebound", "Hardcover");
gsub("Slipcased Hardcover", "Hardcover");
gsub("Pasta dura", "Hardcover");
gsub("hardcover", "Hardcover");
gsub("Over-Sized 12"W x 16"H Hardcover", "Hardcover");
gsub("hardback", "Hardcover");
gsub("Hardcovere Ausgabe", "Hardcover");
gsub("Broschiert", "Paperback");
gsub("Broché", "Paperback");
gsub("文庫", "Paperback");
gsub("Capa Comum", "Paperback");
gsub("Sewn Paperback With Dust Jacket", "Paperback");
gsub("Pasta Blanda", "Paperback");
gsub("Saddle-Stitched Paperback == 120 X 190 Mm", "Paperback");
gsub("paperback", "Paperback");
gsub("Capa comum", "Paperback");
gsub("Sewn Paperback with dust jacket", "Paperback");
gsub("Sewn paperback with dust jacket", "Paperback");
gsub("Pasta blanda", "Paperback");
gsub("Saddle-stitched Paperback", "Paperback");
gsub("Saddle-stitched paperback", "Paperback");
gsub("120 x 190 mm", "Paperback");
gsub("Hardcover, Paperback", "Paperback And Deluxe Hardcover");
gsub("Paperback and Deluxe Hardcover", "Paperback And Deluxe Hardcover");
gsub("Mass_Market", "Mass Market Paperback");
gsub("Mass Market", "Mass Market Paperback");
gsub("mass_market", "Mass Market Paperback");
gsub("Perfect Paperback", "Mass Market Paperback");
gsub("perfect", "Mass Market Paperback");
gsub("Perfect", "Mass Market Paperback");
gsub("Taschenbuch", "Mass Market Paperback");
gsub("Poche", "Mass Market Paperback");
gsub("Softcover", "Mass Market Paperback");
gsub("Soft Cover", "Mass Market Paperback");
gsub("pocket", "Mass Market Paperback");
gsub("Mass Market Paperback Paperback", "Mass Market Paperback");
gsub("soft cover", "Mass Market Paperback");
gsub("softcover", "Mass Market Paperback");
gsub("Pocket", "Mass Market Paperback");
gsub("Textbook Binding", "Textbook");
gsub("Board Book", "Board Books");
gsub("Board Bookss", "Board Books");
gsub("Board", "Board Books");
gsub("Board book", "Board Books");
gsub("Board Books Books", "Board Books");
gsub("Board Books book", "Board Books");
gsub("Nook", "Ebook");
gsub("Kindle Edition", "Ebook");
gsub("ebook", "Ebook");
gsub("Ebook with Audiobook/Video", "Ebook");
gsub("Audio Cd", "Audiobook");
gsub("Audiobook CD", "Audiobook");
gsub("Audio", "Audiobook");
gsub("Audio Cassette", "Audiobook");
gsub("Audiobook Cassette", "Audiobook");
gsub("Audiobook (NTSC)", "Audiobook");
gsub("Audiobook Play", "Audiobook");
gsub("Audiobookcd", "Audiobook");
gsub("Mp3 Book", "Audiobook");
gsub("Mp3 Cd", "Audiobook");
gsub("Audio Play", "Audiobook");
gsub("Audible Audio", "Audiobook");
gsub("Audiocd", "Audiobook");
gsub("Cd-Rom", "Audiobook");
gsub("Kindle Edition With Audio/Video", "Audiobook");
gsub("Dvd", "Audiobook");
gsub("Dvd (Ntsc)", "Audiobook");
gsub("Audio CD", "Audiobook");
gsub("DVD (NTSC)", "Audiobook");
gsub("MP3 Book", "Audiobook");
gsub("MP3 CD", "Audiobook");
gsub("DVD", "Audiobook");
gsub("Audiobookbook", "Audiobook");
gsub("Kindle Edition with Audio/Video", "Audiobook");
gsub("CD-ROM", "Audiobook");
gsub("Spiral", "Spiral-Bound");
gsub("Spiral=Bound", "Spiral-Bound");
gsub("spiral=bound", "Spiral-Bound");
gsub("Spiral-Bound-bound", "Spiral-Bound");
gsub("Boxed Set - Hardcover", "Boxed Set");
gsub("Bookprint", "Boxed Set");
gsub("Boxed Collection", "Boxed Set");
gsub("Boxed set", "Boxed Set");
gsub("Library", "Library Binding");
gsub("Library Binding Binding", "Library Binding");
gsub("Comic", "Comics");
gsub("Comicss", "Comics");
gsub("コミック", "Comics");
gsub("Brochura", "Pamphlet");
gsub("78 Card Tarot Deck", "Deck of 78 Tarot Cards");
gsub("Paperback W/Cd", "Paperback with CD");
gsub("Paperback with Cd Rom", "Paperback with CD");
gsub("Paperback w/ CD", "Paperback with CD");
gsub("Paperback with CD Rom", "Paperback with CD");
gsub("Loose Leaf", "Paper");
gsub("Looseleaf", "Paper");
gsub("paper", "Paper");
gsub("3-Ring Binder", "Ringbound");
gsub("3-ring Binder", "Ringbound");
gsub("Tarot Cards & Book", "Tarot Deck & Book");
gsub("Tarot Deck And Booklet", "Tarot Deck & Book");
gsub("Tarot Deck & Booklet", "Tarot Deck & Book");
gsub("Tarot Deck and Booklet", "Tarot Deck & Book");
gsub("Tarot Deck Tarot Cards & Book Book", "Tarot Deck & Book");
gsub("Tarot Deck Tarot Deck and Booklet Book", "Tarot Deck & Book");
gsub("Tarot Deck Tarot Deck & Booklet Book", "Tarot Deck & Book");
gsub("Tarot Deck Tarot Deck Tarot Cards & Book Book Book", "Tarot Deck & Book");
gsub("Tarot Deck Tarot Deck Tarot Deck and Booklet Book Book", "Tarot Deck & Book");
gsub("Tarot Deck Tarot Deck Tarot Deck & Booklet Book Book", "Tarot Deck & Book");
gsub("Paperback with deck of cards", "Paperback with Deck of Cards");
print}' OFS=", " processed/joined_book_data.csv > processed/cleaned_bookformat.csv