bin/post -c books_no_schema /data/everything_part_1_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_2_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_3_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_4_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_5_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_6_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_7_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_8_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_9_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_10_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_11_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_12_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_13_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_14_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_15_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_16_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_17_mood_remastered.json
bin/post -c books_no_schema /data/everything_part_18_mood_remastered.json
