bin/post -c books_no_schema /data/everything_part_1_mood.json
bin/post -c books_no_schema /data/everything_part_2_mood.json
bin/post -c books_no_schema /data/everything_part_3_mood.json
bin/post -c books_no_schema /data/everything_part_4_mood.json
bin/post -c books_no_schema /data/everything_part_5_mood.json
bin/post -c books_no_schema /data/everything_part_6_mood.json
bin/post -c books_no_schema /data/everything_part_7_mood.json
bin/post -c books_no_schema /data/everything_part_8_mood.json
bin/post -c books_no_schema /data/everything_part_9_mood.json
bin/post -c books_no_schema /data/everything_part_10_mood.json
bin/post -c books_no_schema /data/everything_part_11_mood.json
bin/post -c books_no_schema /data/everything_part_12_mood.json
bin/post -c books_no_schema /data/everything_part_13_mood.json
bin/post -c books_no_schema /data/everything_part_14_mood.json
bin/post -c books_no_schema /data/everything_part_15_mood.json
bin/post -c books_no_schema /data/everything_part_16_mood.json
bin/post -c books_no_schema /data/everything_part_17_mood.json
bin/post -c books_no_schema /data/everything_part_18_mood.json
