FROM solr:8.10

# Copy synonyms file
COPY synonyms.txt /data/synonyms.txt

# Copy files
COPY everything_part_1_mood_remastered.json /data/everything_part_1_mood_remastered.json
COPY everything_part_2_mood_remastered.json /data/everything_part_2_mood_remastered.json
COPY everything_part_3_mood_remastered.json /data/everything_part_3_mood_remastered.json
COPY everything_part_4_mood_remastered.json /data/everything_part_4_mood_remastered.json
COPY everything_part_5_mood_remastered.json /data/everything_part_5_mood_remastered.json
COPY everything_part_6_mood_remastered.json /data/everything_part_6_mood_remastered.json
COPY everything_part_7_mood_remastered.json /data/everything_part_7_mood_remastered.json
COPY everything_part_8_mood_remastered.json /data/everything_part_8_mood_remastered.json
COPY everything_part_9_mood_remastered.json /data/everything_part_9_mood_remastered.json
COPY everything_part_10_mood_remastered.json /data/everything_part_10_mood_remastered.json
COPY everything_part_11_mood_remastered.json /data/everything_part_11_mood_remastered.json
COPY everything_part_12_mood_remastered.json /data/everything_part_12_mood_remastered.json
COPY everything_part_13_mood_remastered.json /data/everything_part_13_mood_remastered.json
COPY everything_part_14_mood_remastered.json /data/everything_part_14_mood_remastered.json
COPY everything_part_15_mood_remastered.json /data/everything_part_15_mood_remastered.json
COPY everything_part_16_mood_remastered.json /data/everything_part_16_mood_remastered.json
COPY everything_part_17_mood_remastered.json /data/everything_part_17_mood_remastered.json
COPY everything_part_18_mood_remastered.json /data/everything_part_18_mood_remastered.json


# Copy schema file
COPY books_schema.json /data/books_schema.json

COPY startup.sh ./scripts/startup.sh

ENTRYPOINT ["./scripts/startup.sh"]
